name: Test(linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        jand-version: [v0.7.0, v0.7.1]
    steps:
    - uses: actions/checkout@v3
    
    - name: Download JanD
      run: wget https://github.com/Jan0660/JanD/releases/download/${{ matrix.jand-version }}/jand-linux-x64-aot
    
    - name: Install JanD
      run: sudo mv jand-linux-x64-aot /usr/bin/jand
    
    - name: Fix permission of JanD executable
      run: chmod 777 /usr/bin/jand

    - name: Run JanD in background
      run: jand start-daemon &
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install npm modules
      run: npm i
    
    - run: npm test

    - name: Upload JanD log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: JanD Log
        path: daemon.log
